spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=yes
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #thymeleft配置
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8088
